[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
cache = true
cache_path = "cache"
broadcast = "broadcast"
gas_reports = ["*"]
gas_reports_ignore = []
solc-version = "0.8.26"
optimizer = false
verbosity = 3
ignored_error_codes = []
block_number = 17_740_856
block_timestamp = 1_689_934_508
# Ignore base test files to avoid running tests twice
no_match_path = "./test/base/*.t.sol"

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 512
depth = 25
fail_on_revert = true

[profile.production]
evm_version = "cancun"
optimizer = true
optimizer_runs = 999999
build_info = true
sizes = true
